version: "3.8"

services:
    # image project
    app:
        container_name: tal7aouy-laravel
        build:
            context: .
            dockerfile: Dockerfile
        image: tal7aouy/laravel-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        depends_on: 
            - redis
        networks: 
            - laravel
    
    # nginx
    nginx:
        container_name: tal7aouy-nginx
        image: nginx:latest
        restart: unless-stopped
        ports: 
            - "8000:80"
        volumes: 
            - ./:/var/www
            - ./docker/nginx/:/etc/nginx/conf.d/
        networks: 
            - laravel

    # db mysql
    mysql:
        container_name: tal7aouy-mysql
        image: mysql:8
        restart: unless-stopped
        environment: 
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
        volumes: 
            - ./.docker/mysql/dbdata:/var/lib/mysql
        ports: 
            - "3388:3306"
        networks: 
            - laravel

    # queue
    queue:
        container_name: tal7aouy-queue
        image: tal7aouy/laravel-app
        restart: unless-stopped
        command: "php artisan queue:work"
        volumes: 
            - ./:/var/www
        depends_on: 
            - redis
            - app
        networks: 
            - laravel

    # redis
    redis:
        container_name: tal7aouy-redis
        image: redis:latest
        networks: 
            - laravel

networks: 
    laravel:
        driver: bridge
